
###################
### KEYBINDINGS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/
$Mod = SUPER # Sets "Windows" key as main modifier

# Example binds, see https://wiki.hypr.land/Configuring/Binds/ for more
bind = $Mod, Q, killactive,
bind = $Mod, M, exit,
bind = $Mod, F, togglefloating,
bind = $Mod SHIFT, P, pseudo, # dwindle
bind = $Mod, S, togglesplit, # dwindle
bind = $Mod, L, exec, wlogout

# Launch Programs Bninds
bind = $Mod, Return, exec, $terminal
bind = $Mod, E, exec, $filemanager
bind = $Mod, W, exec, $browser
bind = $Mod Control, W, exec, $browser2
bind = $Mod, O, exec, obsidian
bind = $Mod SHIFT, O, exec, codium
bind = $Mod, B, exec, ~/.config/waybar/scripts/launcher.sh
# bind = $Mod, B, exec, qs -c noctalia-shell ipc call bar toggle

# Menu Binds
bind = $Mod ALT, Return, exec, $ROFI_PATH/$menu
bind = $Mod Control, Return, exec, $ROFI_PATH/scripts/capn-menu.sh
bind = $Mod, V, exec, $ROFI_PATH/scripts/clipboard-history.sh
bind = $Mod SHIFT, W, exec, $ROFI_PATH/scripts/wallpapers.sh
#bind = $Mod SHIFT, W, exec, qs -c noctalia-shell ipc call wallpaper toggle
bind = $Mod SHIFT, Return, exec, $ROFI_PATH/scripts/projects_menu.sh
bind = $Mod SHIFT Control, Return, exec, $ROFI_PATH/scripts/tmux_sessions.sh
bind = $Mod SHIFT ALT, Return, exec, $ROFI_PATH/scripts/kill_tmux_sessions.sh

# Screen Capture Binds
bind = $Mod, C, exec, grim -g "$(slurp)" /home/capn/Pictures/captures/$(date +'%s_grim.png')

# Move focus with mainMod + arrow keys
bind = $Mod, left, movefocus, l
bind = $Mod, h, movefocus, l
bind = $Mod, right, movefocus, r
bind = $Mod, l, movefocus, r
bind = $Mod, up, movefocus, u
bind = $Mod, k, movefocus, u
bind = $Mod, down, movefocus, d
bind = $Mod, J, movefocus, d

# Switch workspaces with mainMod + [0-9]
bind = $Mod, 1, workspace, 1
bind = $Mod, 2, workspace, 2
bind = $Mod, 3, workspace, 3
bind = $Mod, 4, workspace, 4
bind = $Mod, 5, workspace, 5
bind = $Mod, 6, workspace, 6
bind = $Mod, 7, workspace, 7
bind = $Mod, 8, workspace, 8
bind = $Mod, 9, workspace, 9
bind = $Mod, 0, workspace, 10

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $Mod SHIFT, 1, movetoworkspace, 1
bind = $Mod SHIFT, 2, movetoworkspace, 2
bind = $Mod SHIFT, 3, movetoworkspace, 3
bind = $Mod SHIFT, 4, movetoworkspace, 4
bind = $Mod SHIFT, 5, movetoworkspace, 5
bind = $Mod SHIFT, 6, movetoworkspace, 6
bind = $Mod SHIFT, 7, movetoworkspace, 7
bind = $Mod SHIFT, 8, movetoworkspace, 8
bind = $Mod SHIFT, 9, movetoworkspace, 9
bind = $Mod SHIFT, 0, movetoworkspace, 10

# Example special workspace (scratchpad)
bind = $Mod, S, togglespecialworkspace, magic
bind = $Mod SHIFT, S, movetoworkspace, special:magic

# Scroll through existing workspaces with mainMod + scroll
bind = $Mod, mouse_down, workspace, e+1
bind = $Mod, mouse_up, workspace, e-1

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $Mod, mouse:272, movewindow
bindm = $Mod, mouse:273, resizewindow

# Laptop multimedia keys for volume and LCD brightness
bindel = ,XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
bindel = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindel = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindel = ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindel = ,XF86MonBrightnessUp, exec, brightnessctl -e4 -n2 set 5%+
bindel = ,XF86MonBrightnessDown, exec, brightnessctl -e4 -n2 set 5%-

# Requires playerctl
bindl = , XF86AudioNext, exec, playerctl next
bindl = , XF86AudioPause, exec, playerctl play-pause
bindl = , XF86AudioPlay, exec, playerctl play-pause
bindl = , XF86AudioPrev, exec, playerctl previous



